DisqusShortname = ""
GoogleAnalytics = ""
baseURL = "https://gestsol.github.io/pasajes-chile-noticias/"
canonifyURLs = true
languageCode = "es-es"
subtitle = "Sitio Oficial de Pasajes Chile Noticias"
theme = "hugo-travelify-theme"
themesDir = "themes"
title = "Pasajes Chile Noticias"
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 20
[[menu.main]]
name = "About"
url = "/about/"
weight = 10
[params]
avatar = "css/images/avatar.png"
copyright = "Copyright PasajesChile 2017"
custom_css = []
custom_js = []
date_format = "01 January, 2017"
disable_mathjax = false
logo = "css/images/logo.png"
site_description = "El portal donde te daremos toda la informac√≠on para que viajes cuando quieras y como quieras. Tu decides..."
[params.slider]
enable = true
num_features = 6
[params.widgets]
archives = false
categories = true
recent_articles = false
search = true
tag_cloud = false
tags = true
[social]
facebook = "pasajeschile"
flickr = ""
github = ""
googleplus = ""
instagram = "pasajeschile"
linkedin = ""
pinterest = ""
tumblr = ""
twitter = "pasajeschile"
vimeo = ""
youtube = "pasajeschile"
